# Generated by Django 4.2.5 on 2023-10-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0005_cart_remove_shoppingcart_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.SmallIntegerField(default=0),
        ),
    ]
