# Generated by Django 4.2.5 on 2023-10-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0010_alter_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Processing', 'Processing')], default='Processing', max_length=20),
        ),
    ]
